// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.4
// source: user_proto/user.proto

package user_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *UserId) Reset() {
	*x = UserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserName) Reset() {
	*x = UserName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserName) ProtoMessage() {}

func (x *UserName) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserName.ProtoReflect.Descriptor instead.
func (*UserName) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserAge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age uint64 `protobuf:"varint,1,opt,name=Age,proto3" json:"Age,omitempty"`
}

func (x *UserAge) Reset() {
	*x = UserAge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAge) ProtoMessage() {}

func (x *UserAge) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAge.ProtoReflect.Descriptor instead.
func (*UserAge) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserAge) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

type UserSex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sex string `protobuf:"bytes,1,opt,name=Sex,proto3" json:"Sex,omitempty"`
}

func (x *UserSex) Reset() {
	*x = UserSex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSex) ProtoMessage() {}

func (x *UserSex) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSex.ProtoReflect.Descriptor instead.
func (*UserSex) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserSex) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

var File_user_proto_user_proto protoreflect.FileDescriptor

var file_user_proto_user_proto_rawDesc = []byte{
	0x0a, 0x15, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x65, 0x6e, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x22, 0x18, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x07, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x41, 0x67, 0x65, 0x22, 0x1b, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x53, 0x65, 0x78, 0x32, 0xf5, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x4f, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x65, 0x6e, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x21, 0x2e, 0x65, 0x6e, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x00, 0x12, 0x4d,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x65, 0x6e, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x20, 0x2e, 0x65, 0x6e, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x53, 0x65, 0x78, 0x12, 0x1f, 0x2e, 0x65, 0x6e, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x63, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x20, 0x2e, 0x65, 0x6e, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x78, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32,
	0x67, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x75, 0x64, 0x6f, 0x6e, 0x67, 0x6b, 0x75, 0x6e, 0x2f, 0x75, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_proto_user_proto_rawDescOnce sync.Once
	file_user_proto_user_proto_rawDescData = file_user_proto_user_proto_rawDesc
)

func file_user_proto_user_proto_rawDescGZIP() []byte {
	file_user_proto_user_proto_rawDescOnce.Do(func() {
		file_user_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_proto_user_proto_rawDescData)
	})
	return file_user_proto_user_proto_rawDescData
}

var file_user_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_proto_user_proto_goTypes = []interface{}{
	(*UserId)(nil),   // 0: enlight.service.ucenter.UserId
	(*UserName)(nil), // 1: enlight.service.ucenter.UserName
	(*UserAge)(nil),  // 2: enlight.service.ucenter.UserAge
	(*UserSex)(nil),  // 3: enlight.service.ucenter.UserSex
}
var file_user_proto_user_proto_depIdxs = []int32{
	0, // 0: enlight.service.ucenter.User.GetName:input_type -> enlight.service.ucenter.UserId
	0, // 1: enlight.service.ucenter.User.GetAge:input_type -> enlight.service.ucenter.UserId
	0, // 2: enlight.service.ucenter.User.GetSex:input_type -> enlight.service.ucenter.UserId
	1, // 3: enlight.service.ucenter.User.GetName:output_type -> enlight.service.ucenter.UserName
	2, // 4: enlight.service.ucenter.User.GetAge:output_type -> enlight.service.ucenter.UserAge
	3, // 5: enlight.service.ucenter.User.GetSex:output_type -> enlight.service.ucenter.UserSex
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_user_proto_init() }
func file_user_proto_user_proto_init() {
	if File_user_proto_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_proto_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_proto_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_user_proto_goTypes,
		DependencyIndexes: file_user_proto_user_proto_depIdxs,
		MessageInfos:      file_user_proto_user_proto_msgTypes,
	}.Build()
	File_user_proto_user_proto = out.File
	file_user_proto_user_proto_rawDesc = nil
	file_user_proto_user_proto_goTypes = nil
	file_user_proto_user_proto_depIdxs = nil
}
