// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user_proto/user.proto

package user_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	GetName(ctx context.Context, in *UserId, opts ...client.CallOption) (*UserName, error)
	GetAge(ctx context.Context, in *UserId, opts ...client.CallOption) (*UserAge, error)
	GetSex(ctx context.Context, in *UserId, opts ...client.CallOption) (*UserSex, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetName(ctx context.Context, in *UserId, opts ...client.CallOption) (*UserName, error) {
	req := c.c.NewRequest(c.name, "User.GetName", in)
	out := new(UserName)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetAge(ctx context.Context, in *UserId, opts ...client.CallOption) (*UserAge, error) {
	req := c.c.NewRequest(c.name, "User.GetAge", in)
	out := new(UserAge)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetSex(ctx context.Context, in *UserId, opts ...client.CallOption) (*UserSex, error) {
	req := c.c.NewRequest(c.name, "User.GetSex", in)
	out := new(UserSex)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	GetName(context.Context, *UserId, *UserName) error
	GetAge(context.Context, *UserId, *UserAge) error
	GetSex(context.Context, *UserId, *UserSex) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		GetName(ctx context.Context, in *UserId, out *UserName) error
		GetAge(ctx context.Context, in *UserId, out *UserAge) error
		GetSex(ctx context.Context, in *UserId, out *UserSex) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) GetName(ctx context.Context, in *UserId, out *UserName) error {
	return h.UserHandler.GetName(ctx, in, out)
}

func (h *userHandler) GetAge(ctx context.Context, in *UserId, out *UserAge) error {
	return h.UserHandler.GetAge(ctx, in, out)
}

func (h *userHandler) GetSex(ctx context.Context, in *UserId, out *UserSex) error {
	return h.UserHandler.GetSex(ctx, in, out)
}
